import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ReactElement } from 'react'
import NavWithSidebarLayout from '../../layouts/navWithSidebarLayout'
import styles from '../styles/Home.module.css'
import { NextPageWithLayout } from '../_app'

const SampleHome: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Group Budget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto px-4">
        <h1>Hello World</h1>

        <div className="card lg:card-side bg-base-100 shadow-xl">
          <figure><img src="https://api.lorem.space/image/album?w=400&h=400" alt="Album"/></figure>
          <div className="card-body">
            <h2 className="card-title">New album is released!</h2>
            <p>Click the button to listen on Spotiwhy app.</p>
            <div className="card-actions justify-end">
              <button className="btn btn-primary">Listen</button>
            </div>
          </div>
        </div>

      </div>
    </>
  )
}

SampleHome.getLayout = function getLayout(page: ReactElement) {
  return (
    <NavWithSidebarLayout>
      {page}
    </NavWithSidebarLayout>
  )
}


export default SampleHome
