import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ReactElement } from 'react'
import NavLayout from '../layouts/navLayout'
import styles from '../styles/Home.module.css'
import { NextPageWithLayout } from './_app'

const SampleHome: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Group Budget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Hi World</h2>

    </>
  )
}

SampleHome.getLayout = function getLayout(page: ReactElement) {
  return (
    <NavLayout>
      {page}
    </NavLayout>
  )
}

export default SampleHome
